name: 定时生成日志

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 追加增强版日志
        run: |
          week=$(date +%A)
          text_array=("坚持敲代码！" "今天也要加油！" "定时任务运行成功~" "软件工程冲冲冲！")
          random_text=${text_array[$RANDOM % ${#text_array[@]}]}
          echo "【ST】执行时刻: $(date) ,星期: $week ,寄语: $random_text" >> log.txt

      - name: 提交推送
        run: |
          git config --global user.name "github‑actions‑bot"
          git config --global user.email "actions@github.com"
          git add log.txt
          git commit -m "增强日志更新 $(date)"
          git push
